### ISSUE TITLE
Are globbing patterns supported?

### ISSUE THREAD

**Issue by oleersoy** [RyanZim/postcss-uncss#3]
Before I was using the gulp uncss plugin like this:

``` js
  return gulp.src(PLI.SRC_MAIN_CSS)
    .pipe(pc(pre_uncss_processors))
    .pipe(uncss({
      html: [PLI.TARGET_MAIN_HTML]
    }))
```

The `PLI.TARGET_MAIN_HTML` is just a globbing string like this `PLI.TARGET_MAIN_HTML = path.join(PLI.target.main.html, GLOB.ALL_HTML);`.  It selects all the html in the main directory.

I'm trying to switch over to the postcss uncss plugin.  I have the processors configured like this:

``` js
var pc_uncss = require('postcss-uncss');

var uncss_processors = [..., autoprefixer, pc_uncss({html: [PLI.TARGET_MAIN_HTML]}), pc_reporter({
  clearMessages: true
})];
```
So I moved the globbing string from the plugin configuration to the postcss plugin configuration, but now I get messages like this:

``` console
[15:19:07] Using gulpfile ~/Junk/@superflycss/component-link/gulpfile.js
[15:19:07] Starting 'deploy:test:css'...

events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: UnCSS: no HTML files found
    at getHTML (/home/ole/Junk/@superflycss/component-link/node_modules/uncss/src/uncss.js:32:31)
    at process (/home/ole/Junk/@superflycss/component-link/node_modules/uncss/src/uncss.js:223:20)
    at /home/ole/Junk/@superflycss/component-link/node_modules/uncss/src/uncss.js:249:16
    at LazyResult.run (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:185:32)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/home/ole/Junk/@superflycss/component-link/node_modules/postcss/lib/lazy-result.js:197:22)

```

Are globbing patterns supported?

**Comment by RyanZim** [comment]
They are; what's the exact value of `PLI.TARGET_MAIN_HTML`?

**Comment by oleersoy** [comment]
target/main/html/**/*.html

**Comment by RyanZim** [comment]
@oleersoy Try using an absolute path instead.

**Comment by oleersoy** [comment]
@RyanZim tried it (But same result):
```
var uncss_processors = [pc_import, pc_each, pc_for, pc_custom_properties, pc_apply, pc_calc, pc_color_function, pc_sass_color_functions, pc_custom_media, pc_font_magician, autoprefixer, pc_uncss({html: ['target/main/html/**/*.html']}), pc_reporter({
```
I also updated the [link component](https://github.com/superflycss/component-link) repository with this task for testing.  If you:
``` console
git clone https://github.com/superflycss/component-link
npm run deploy
``` 
You should get the same error.  When I tried hard coding the glob I did:
``` console
cd component-link
atom node_modules/@superflycss/task-deploy/src/main/js/index.js
```
Then hard code the glob pattern.  Run `gulp deploy:test:css` and the result should be the same.

**Comment by RyanZim** [comment]
@oleersoy I meant an absolute path (i.e. from the root of your filesystem)

    path.join(path.resolve('target/main/html'), '**/*.html')

**Comment by oleersoy** [comment]
Tried it - Same result:
```
var uncss_processors = [pc_import, pc_each, pc_for, pc_custom_properties, pc_apply, pc_calc, pc_color_function, pc_sass_color_functions, pc_custom_media, pc_font_magician, autoprefixer, pc_uncss({html: [path.join(path.resolve('target/main/html'), '**/*.html')]}), pc_reporter({
  clearMessages: true
})];
```

BTW - The constant that I'm working with comes from [@superflycss/pli](https://github.com/superflycss/pli).  I'm using this constant in all [these dependents](https://www.npmjs.com/package/@superflycss/pli) and it's working fine.

**Comment by RyanZim** [comment]
Do a `console.log` of `path.join(path.resolve('target/main/html'), '**/*.html')`; is it the correct path?

**Comment by oleersoy** [comment]
I have a monkey brain!  It's supposed to be PLI.TARGET_TEST_CSS ... and I used MAIN instead of TEST.  It's working great now.  Thanks for all your very patient help.

**Comment by oleersoy** [comment]
Here's the [npm installable](https://github.com/superflycss/task-deploy) task in case anyone wants a future reference point / example.  One of the things that was not immediately obvious to me (As I'm bopping around in java / css / docker / and 50 other things) was how to configure the plugin.  So if the usage snippet in the readme declared a few configuration examples such as:

## Usage
```
postcss([ require('postcss-uncss')({html: ['src/**/*.html']}) ])
```
That would have been helpful (At least for me).

**Comment by oleersoy** [comment]
I'm also running into an infinite loop bug, but I think it's uncss core.  Just linking here in FYI:
https://github.com/giakki/uncss/issues/319
