### ISSUE TITLE
css.walkRules is not a function

### ISSUE THREAD

**Issue by JTLR** [RyanZim/postcss-uncss#6]
Hi, I've setup my gulp build to use gulp-postcss and postcss-uncss (8.0.0 and 0.16.1 respectively).

When trying to run uncss I get the following error:

[16:07:44] Using gulpfile C:\xampp\htdocs\site\gulpfile.js
[16:07:44] Starting 'ampSass'...

events.js:136
      throw er; // Unhandled 'error' event
      ^
TypeError: css.walkRules is not a function
    at getUsedSelectors (C:\xampp\htdocs\site\node_modules\uncss\src\lib.js:134:9)
    at Promise.all.pages.map (C:\xampp\htdocs\site\node_modules\uncss\src\lib.js:234:44)
    at Array.map (<anonymous>)
    at uncss (C:\xampp\htdocs\site\node_modules\uncss\src\lib.js:234:30)
    at processAsPostCss (C:\xampp\htdocs\site\node_modules\uncss\src\uncss.js:214:12)
    at resource.then (C:\xampp\htdocs\site\node_modules\uncss\src\uncss.js:226:20)
    at <anonymous>

Any ideas what this could be?

**Comment by RyanZim** [comment]
Nope, no ideas. @w0rm?

**Comment by JTLR** [comment]
Any ideas on this?

**Comment by albertvolkman** [comment]
See if this fixes the issue for you-

https://github.com/uncss/uncss/issues/287#issuecomment-320796167
